services:
  frontend:
    build:
      context: frontend/docker
      dockerfile: development/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "20080:80"
    volumes:
      - /var/www/.composer-docker/cache:/root/.composer/cache:delegated
      - ./frontend:/app
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      FRONTEND_NAME: App Frontend
      DB_DSN_PREFIX: pgsql
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD_FILE: /run/secrets/app_db_password
      COOKIE_DOMAIN: ${DOMAIN}
      FRONTEND_URL: https://${DOMAIN}
      BACKEND_URL: https://cp.${DOMAIN}
      STATIC_URL: https://static.${DOMAIN}
      MAILER_FROM_EMAIL: no-reply@${DOMAIN}
      MAILER_FROM_NAME: ${APP_NAME}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILER_USERNAME: ${MAILER_USERNAME}
      MAILER_PASSWORD_FILE: /run/secrets/app_mailer_password
      MAILER_ENCRYPTION: tls
    secrets:
      - app_db_password
      - app_mailer_password
    networks:
      - gmtx_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: backend/docker
      dockerfile: development/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "21080:80"
    volumes:
      - /var/www/.composer-docker/cache:/root/.composer/cache:delegated
      - ./backend:/app
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      BACKEND_NAME: App Backend
      DB_DSN_PREFIX: pgsql
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD_FILE: /run/secrets/app_db_password
      COOKIE_DOMAIN: ${DOMAIN}
      FRONTEND_URL: https://${DOMAIN}
      BACKEND_URL: https://cp.${DOMAIN}
      STATIC_URL: https://static.${DOMAIN}
      MAILER_FROM_EMAIL: no-reply@${DOMAIN}
      MAILER_FROM_NAME: ${APP_NAME}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILER_USERNAME: ${MAILER_USERNAME}
      MAILER_PASSWORD_FILE: /run/secrets/app_mailer_password
      MAILER_ENCRYPTION: tls
    secrets:
      - app_db_password
      - app_mailer_password
    networks:
      - gmtx_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  static:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "22080:80"
    volumes:
      - /var/www/static:/usr/share/nginx/html:ro
    networks:
      - gmtx_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password
    secrets:
      - app_db_password
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - gmtx_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 3

secrets:
  app_db_password:
    file: ./secrets/production/app_db_password
  app_mailer_password:
    file: ./secrets/production/app_mailer_password

networks:
  gmtx_net:
    name: gmtx_net
    external: true
