services:
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
      - static
    networks:
      - gmtx_net
    restart: unless-stopped

  frontend:
    build:
      context: frontend/docker
      dockerfile: development/nginx/Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - /var/www/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    environment:
      APP_ENV: dev
      APP_DEBUG: 0
      FRONTEND_NAME: App Frontend
      DB_DSN_PREFIX: pgsql
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD_FILE: /run/secrets/app_db_password
      COOKIE_DOMAIN: ${DOMAIN}
      FRONTEND_URL: https://${DOMAIN}
      BACKEND_URL: https://cp.${DOMAIN}
      STATIC_URL: https://static.${DOMAIN}
      MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
      MAILER_FROM_NAME: ${APP_NAME}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILER_USERNAME: ${MAILER_USERNAME}
      MAILER_PASSWORD_FILE: /run/secrets/app_mailer_password
      MAILER_ENCRYPTION: tls
    secrets:
      - app_db_password
      - app_mailer_password
    networks:
      - gmtx_net

  backend:
    build:
      context: backend/docker
      dockerfile: development/nginx/Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - /var/www/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    environment:
      APP_ENV: dev
      APP_DEBUG: 0
      BACKEND_NAME: App Backend
      DB_DSN_PREFIX: pgsql
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD_FILE: /run/secrets/app_db_password
      COOKIE_DOMAIN: ${DOMAIN}
      FRONTEND_URL: https://${DOMAIN}
      BACKEND_URL: https://cp.${DOMAIN}
      STATIC_URL: https://static.${DOMAIN}
      MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
      MAILER_FROM_NAME: ${APP_NAME}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILER_USERNAME: ${MAILER_USERNAME}
      MAILER_PASSWORD_FILE: /run/secrets/app_mailer_password
      MAILER_ENCRYPTION: tls
    secrets:
      - app_db_password
      - app_mailer_password
    networks:
      - gmtx_net

  static:
    image: nginx:alpine
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - /var/www/static:/usr/share/nginx/html:ro
    networks:
      - gmtx_net

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password
    secrets:
      - app_db_password
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - gmtx_net

volumes:
  caddy_data:
  caddy_config:


secrets:
  app_db_password:
    file: ./secrets/production/app_db_password
  app_mailer_password:
    file: ./secrets/production/app_mailer_password

networks:
  gmtx_net:
    name: gmtx_net
    driver: bridge
