services:
  frontend:
    build:
      context: frontend/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    environment:
      APP_ENV: dev
      APP_DEBUG: 0
      FRONTEND_NAME: App Frontend
      DB_DSN_PREFIX: pgsql
      DB_HOST: postgres
      DB_NAME: app
      DB_USER: app
      DB_PASSWORD_FILE: /run/secrets/app_db_password
      COOKIE_DOMAIN: localhost
      FRONTEND_URL: https://gmtx.ru
      BACKEND_URL: https://cp.gmtx.ru
      STATIC_URL: https://static.gmtx.ru
      MAILER_FROM_EMAIL: support@audetv.ru
      MAILER_FROM_NAME: application
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD_FILE: /run/secrets/app_mailer_password
      MAILER_ENCRYPTION: tls
      MANTICORE_HOST: ${MANTICORE_HOST}
      MANTICORE_PORT: ${MANTICORE_PORT}
      MANTICORE_API_KEY: ${MANTICORE_API_KEY}
    secrets:
      - app_db_password
      - app_mailer_password
    networks:
      - gmtx_net

  backend:
    build:
      context: backend/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    environment:
      APP_ENV: dev
      APP_DEBUG: 0
      BACKEND_NAME: App Backend
      DB_DSN_PREFIX: pgsql
      DB_HOST: postgres
      DB_NAME: app
      DB_USER: app
      DB_PASSWORD_FILE: /run/secrets/app_db_password
      COOKIE_DOMAIN: localhost
      FRONTEND_URL: https://gmtx.ru
      BACKEND_URL: https://cp.gmtx.ru
      STATIC_URL: https://static.gmtx.ru
      MAILER_FROM_EMAIL: mail@localhost
      MAILER_FROM_NAME: application
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD_FILE: /run/secrets/app_mailer_password
      MAILER_ENCRYPTION: tls
      MANTICORE_HOST: ${MANTICORE_HOST}
      MANTICORE_PORT: ${MANTICORE_PORT}
      MANTICORE_API_KEY: ${MANTICORE_API_KEY}
    secrets:
      - app_db_password
      - app_mailer_password
    networks:
      - gmtx_net

  static:
    image: nginx:alpine
    ports:
      - 22080:80
    volumes:
      - /mnt/work/gmtx/static:/usr/share/nginx/html:ro
    networks:
      - gmtx_net

  postgres:
    image: postgres:17-alpine
    environment:
      APP_ENV: dev
      POSTGRES_USER: app
      POSTGRES_DB: app
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password
    secrets:
      - app_db_password
    volumes:
      - /mnt/work/gmtx/postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - gmtx_net

  mailer:
    image: mailhog/mailhog
    ports:
      - 1025:8025
    networks:
      - gmtx_net

secrets:
  app_db_password:
    file: ./secrets/development/app_db_password
  app_mailer_password:
    file: ./secrets/development/app_mailer_password

networks:
  gmtx_net:
    name: gmtx_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
    external: true
